# Ported from ~/.config/alacritty/colors.toml
# Static override for the Noctalia dynamic theme (included after it in kitty.conf)

background            #252322
foreground             #dedede

cursor                 #f8f8f0
cursor_text_color      #dedede

selection_foreground   #ffffff
selection_background   #617fa0

color0  #32302e
color1  #ba0e2e
color2  #4e5d84
color3  #617fa0
color4  #95c2e8
color5  #c2dcf2
color6  #ffbb29
color7  #ebebeb

color8  #4d4947
color9  #e61f44
color10 #8391b5
color11 #a1b3c6
color12 #e9f2fa
color13 #ffffff
color14 #ffdb8f
color15 #ffffff
